<template>
    <v-navigation-drawer>
        <v-list>
            <v-list-item>
                <v-list-item-title>Home</v-list-item-title>
            </v-list-item>
            <v-list-item>
                <v-list-item-title>Profile</v-list-item-title>
            </v-list-item>
            <v-list-item>
                <v-list-item-title>Settings</v-list-item-title>
            </v-list-item>
        </v-list>
    </v-navigation-drawer>
</template>
<script></script>
<style></style>
